### ISSUE TITLE
$q.resolve - exists already in angular

### ISSUE THREAD

**Issue by eburi** [insidewhy/angular-promise-extras#11]
Hi,

could $q.resolve be removed, as it already exists in angular?

https://docs.angularjs.org/api/ng/service/$q 
`resolve(value, [successCallback], [errorCallback], [progressCallback]);`

From my point of view the package should only add "extras" and not alter the behavior of the existing $q.
The default $q.resolve handles the case implemented in this library but has additional features. Threrefore this "extra" is kind of a downgrade.

Best regards

**Comment by insidewhy** [comment]
Check the earlier docs, it's in 1.4-1.5 but it isn't in 1.3. I updated the code to only provide it when it doesn't already exist for people stuck on angular 1.3.
