### ISSUE TITLE
angular-promise-extras npm package is old, cannot update it as someone else published it and thus it is not owned by me

### ISSUE THREAD

**Issue by insidewhy** [insidewhy/angular-promise-extras#14]
@mtrias You have published my package, please `npm owner add jpike angular-promise-extras` so I can update my package on the npm registry.

**Comment by mtrias** [comment]
Hey! sorry to be late. I'm on vacation this week. It's done!

**Comment by insidewhy** [comment]
Thanks!

**Comment by mtrias** [comment]
Should we close this issue now ?

**Comment by mtrias** [comment]
Hi @ohjames could you please publish the package to npm ? The last release there is 0.1.3 and it should be 0.1.8.
