### ISSUE TITLE
Prototype pollution vulnerbility

### ISSUE THREAD

**Issue by gabbsmo** [insidewhy/angular-promise-extras#17]
I get the following after running `npm audit`:

```
Moderate        Prototype Pollution

Package         angular

Patched in      >=1.7.9

Dependency of   angular-promise-extras

Path            angular-promise-extras > angular

More info       https://npmjs.com/advisories/1343
```

I have already installed angular 1.7.9 but I assume I still get this error because angular-promise-extras depends on angular < 1.7.0. I could submit a PR if that is OK with the maintainers.

**Comment by insidewhy** [comment]
Fine with me.

**Comment by gabbsmo** [comment]
Submitted PR #18.

**Comment by gabbsmo** [comment]
PR was merged but no release on npm yet. Any way I can help with that?

**Comment by insidewhy** [comment]
@gabbsmo wanna be a maintainer?

**Comment by gabbsmo** [comment]
Sure. Anything I should know before I attempt to publish?

**Comment by insidewhy** [comment]
@gabbsmo not sure, the current maintainer is @mtrias 

I made you a maintainer on github, I can give you access on the npm registry also if you let me know your username there.

**Comment by gabbsmo** [comment]
Just created an account. My username is gabbsmo, same as here on Github.

**Comment by insidewhy** [comment]
@gabbsmo Cool, invited you. Sorry for the delay.

**Comment by gabbsmo** [comment]
@insidewhy Thanks, no problem. Is there any relationship between Github releases and npm packages in this case? Or are they created independently?

**Comment by insidewhy** [comment]
I think you should make them independent and not agree with each other at all. Life is more fun when it is challenging. Especially software development.

**Comment by aurimas4** [comment]
Why it not released on npm yet? :thinking:

**Comment by insidewhy** [comment]
@aurimas4 I don't use angular anymore, @mtrias is maintaining this package, if he doesn't get back to you in a while I can make you a maintainer also if you want?

**Comment by aurimas4** [comment]
Yes, it would be super

**Comment by mtrias** [comment]
Hey! I am also not using this package anymore. So +1 from me to make @aurimas4 a maintainer.

**Comment by aurimas4** [comment]
could you give me access on the npm registry? username same: aurimas4

**Comment by insidewhy** [comment]
@aurimas4 done

**Comment by aurimas4** [comment]
https://www.npmjs.com/package/angular-promise-extras/v/0.1.9
