### ISSUE TITLE
Source not minifyable

### ISSUE THREAD

**Issue by timjacobi** [insidewhy/angular-promise-extras#4]
Due to work regulations I can't provide a pull request now. The `function($delegate)` starting on line 21 is missing the array notation which breaks this library using ngAnnotate.

**Comment by insidewhy** [comment]
You can use `gulp-ng-annotate` or `grunt-ng-annotate` to add the annotations automatically.

**Comment by insidewhy** [comment]
Plus then you won't have to bother with those ugly old annotations for the rest of your code.

**Comment by insidewhy** [comment]
Released 0.1.4 with eaf2cda

**Comment by timjacobi** [comment]
Thanks for the quick turnaround. I had the problem with grunt-ng-annotate. For some reason it didn't pick up the DI'ed function defined in `$provide.decorator`
