### ISSUE TITLE
intermediate value(…) is not a function

### ISSUE THREAD

**Issue by vssathish** [insidewhy/angular-promise-extras#6]
When angular-promise-extra.js is combined with other javascript files it breaks with this error because of missing semi-colon towards the end.

**Comment by insidewhy** [comment]
Duplicate of https://github.com/ohjames/angular-promise-extras/pull/5 I'd suggest using a better concatenator or configuring yours to use "\n;" as a separator.

**Comment by kotmatpockuh** [comment]
"Great" way of solving bug. Most of concatenator break down without ';'. It's not so hard to add ';' at the end of the file!

**Comment by insidewhy** [comment]
I was hoping to encourage people to use better tools and showed how the grunt concatenator could be configured to work around this problem, however you definitely make a very good point and I will add the `;`. Thanks for your encouragement!
